-- Jobseeker PostgreSQL schema.
--
-- This file is the schema of record: it is generated from the live database and is what the
-- application expects to exist. Apply it to an empty database to get a runnable environment.
-- Incremental migration files are kept outside version control; see docs/operations.md.
--
-- Extensions present in the database (managed by the platform, not created here):
--   pg_stat_statements 1.11, pgcrypto 1.3, plpgsql 1.0, supabase_vault 0.3.1, uuid-ossp 1.1
--
-- Not covered here, because it lives outside the public schema:
--   the private storage bucket 'jobseeker-private-state' (backend-only, no storage.objects policies).

create table public.profiles (
  user_id text not null,
  cv_sha256 text not null,
  cv_text text not null,
  document_json jsonb not null,
  source_format text not null,
  original_filename text not null,
  media_type text not null,
  parser_name text not null,
  parser_version text not null,
  search_profiles jsonb not null default '{}'::jsonb,
  updated_at timestamp with time zone not null,
  constraint profiles_pkey PRIMARY KEY (user_id)
);

create table public.telegram_updates (
  update_id bigint not null,
  received_at timestamp with time zone not null default now(),
  state text not null default 'processing'::text,
  attempts integer not null default 1,
  lease_expires_at timestamp with time zone,
  completed_at timestamp with time zone,
  last_error text,
  constraint telegram_update_receipts_state_check CHECK ((state = ANY (ARRAY['processing'::text, 'completed'::text, 'failed'::text]))),
  constraint telegram_updates_pkey PRIMARY KEY (update_id)
);

create table public.usage_events (
  id bigint generated by default as identity,
  user_id text not null,
  kind text not null,
  occurred_at timestamp with time zone not null,
  agent text,
  model text,
  input_tokens bigint not null default 0,
  output_tokens bigint not null default 0,
  cache_read_tokens bigint not null default 0,
  cache_write_tokens bigint not null default 0,
  total_tokens bigint not null default 0,
  cost_usd numeric(14,8) not null default 0,
  constraint usage_events_kind_check CHECK ((kind = ANY (ARRAY['score'::text, 'application'::text, 'search-profile'::text, 'llm'::text]))),
  constraint usage_events_pkey PRIMARY KEY (id)
);

create table public.user_state (
  user_id text not null,
  kind text not null,
  state jsonb not null default '{}'::jsonb,
  expires_at timestamp with time zone not null,
  updated_at timestamp with time zone not null default now(),
  constraint user_state_pkey PRIMARY KEY (user_id, kind)
);

create table public.user_vacancies (
  user_id text not null,
  vacancy_id bigint,
  decision text not null default 'new'::text,
  first_relevant_at timestamp with time zone not null,
  score_updated_at timestamp with time zone,
  updated_at timestamp with time zone not null,
  score integer,
  application_status text,
  application_error text,
  application_requested_at timestamp with time zone,
  application_updated_at timestamp with time zone,
  prefilter_context_hash text,
  prefilter_content_hash text,
  prefilter_regex_score integer,
  prefilter_lexical_cosine double precision,
  prefilter_lexical_score integer,
  prefilter_score integer,
  prefilter_filtered smallint,
  prefilter_audit_selected smallint,
  prefilter_reasons jsonb,
  prefilter_scored_at timestamp with time zone,
  alert_primary_track text,
  alert_summary text,
  alert_reasons jsonb,
  alert_gaps jsonb,
  source text not null,
  source_id text not null,
  search_name text,
  discovered_at timestamp with time zone,
  last_discovered_at timestamp with time zone,
  candidate_context_hash text,
  candidate_listing_hash text,
  candidate_regex_score integer,
  candidate_lexical_cosine double precision,
  candidate_score integer,
  candidate_filtered smallint,
  candidate_reasons jsonb,
  candidate_scored_at timestamp with time zone,
  constraint user_vacancies_application_status_check CHECK ((application_status = ANY (ARRAY['generating'::text, 'ready'::text, 'failed'::text]))),
  constraint user_vacancies_decision_check CHECK ((decision = ANY (ARRAY['new'::text, 'alerted'::text, 'digested'::text, 'skipped'::text, 'applying'::text, 'applied'::text]))),
  constraint user_vacancies_score_check CHECK (((score >= 0) AND (score <= 100))),
  constraint user_vacancies_pkey PRIMARY KEY (user_id, source, source_id)
);

create table public.users (
  user_id text not null,
  chat_id text not null,
  username text,
  display_name text not null,
  status text not null,
  is_owner smallint not null default 0,
  requested_at timestamp with time zone,
  approved_at timestamp with time zone,
  updated_at timestamp with time zone not null,
  delivery_start_minutes integer,
  delivery_end_minutes integer,
  digest_minutes integer,
  delivery_timezone text,
  last_digest_at timestamp with time zone,
  constraint telegram_users_is_owner_check CHECK ((is_owner = ANY (ARRAY[0, 1]))),
  constraint telegram_users_status_check CHECK ((status = ANY (ARRAY['unregistered'::text, 'pending'::text, 'approved'::text, 'rejected'::text, 'revoked'::text]))),
  constraint users_pkey PRIMARY KEY (user_id),
  constraint users_chat_id_key UNIQUE (chat_id)
);

create table public.vacancies (
  id bigint generated by default as identity,
  source text not null,
  source_id text not null,
  apply_id text,
  name text,
  employer text,
  area text,
  salary_from integer,
  salary_to integer,
  salary_currency text,
  salary_gross smallint,
  experience text,
  employment text,
  schedule text,
  work_format text,
  description text,
  key_skills_json jsonb,
  url text not null,
  published_at timestamp with time zone not null,
  source_query text,
  content_hash text,
  canonical_fingerprint text,
  first_seen_at timestamp with time zone not null,
  updated_at timestamp with time zone not null,
  search_vector tsvector generated always as (to_tsvector('simple'::regconfig, ((((((COALESCE(name, ''::text) || ' '::text) || COALESCE(employer, ''::text)) || ' '::text) || COALESCE(description, ''::text)) || ' '::text) || COALESCE((key_skills_json)::text, ''::text)))) stored,
  listing_search_name text,
  listing_title text,
  listing_summary text,
  listing_payload jsonb,
  listing_hash text,
  lifecycle_status text,
  normalized_vacancy_id bigint,
  normalization_attempts integer not null default 0,
  normalization_error text,
  normalization_retry_at timestamp with time zone,
  last_seen_at timestamp with time zone,
  last_checked_at timestamp with time zone,
  constraint vacancies_apply_id_check CHECK ((apply_id ~ '^[a-z]{6}$'::text)),
  constraint vacancies_lifecycle_status_check CHECK ((lifecycle_status = ANY (ARRAY['discovered'::text, 'queued'::text, 'filtered'::text, 'normalizing'::text, 'normalized'::text, 'duplicate'::text, 'failed'::text, 'closed'::text]))),
  constraint vacancies_salary_gross_check CHECK (((salary_gross IS NULL) OR (salary_gross = ANY (ARRAY[0, 1])))),
  constraint vacancies_source_check CHECK ((source = ANY (ARRAY['hh'::text, 'habr'::text, 'rabota'::text, 'hirehi'::text, 'geekjob'::text, 'avito'::text, 'trudvsem'::text, 'ats'::text]))),
  constraint vacancies_pkey PRIMARY KEY (id),
  constraint vacancies_apply_id_key UNIQUE (apply_id),
  constraint vacancies_source_source_id_key UNIQUE (source, source_id)
);

-- Foreign keys are added after every table exists so the file can be applied top to bottom.
alter table public.profiles add constraint profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE;
alter table public.usage_events add constraint usage_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE;
alter table public.user_state add constraint telegram_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE;
alter table public.user_vacancies add constraint user_vacancies_source_fkey FOREIGN KEY (source, source_id) REFERENCES vacancies(source, source_id) ON DELETE CASCADE;
alter table public.user_vacancies add constraint user_vacancies_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE;
alter table public.user_vacancies add constraint user_vacancies_vacancy_id_fkey FOREIGN KEY (vacancy_id) REFERENCES vacancies(id) ON DELETE CASCADE;
alter table public.vacancies add constraint vacancies_normalized_vacancy_id_fkey FOREIGN KEY (normalized_vacancy_id) REFERENCES vacancies(id) ON DELETE SET NULL;

-- Indexes that do not back a constraint.
CREATE INDEX telegram_updates_cleanup_idx ON public.telegram_updates USING btree (received_at);
CREATE INDEX usage_events_kind_time_idx ON public.usage_events USING btree (kind, occurred_at DESC);
CREATE INDEX usage_events_user_kind_time_idx ON public.usage_events USING btree (user_id, kind, occurred_at DESC);
CREATE INDEX user_state_expiry_idx ON public.user_state USING btree (expires_at);
CREATE INDEX user_vacancies_decision_idx ON public.user_vacancies USING btree (user_id, decision);
CREATE INDEX user_vacancies_score_idx ON public.user_vacancies USING btree (user_id, score DESC) WHERE (score IS NOT NULL);
CREATE UNIQUE INDEX user_vacancies_user_normalized_idx ON public.user_vacancies USING btree (user_id, vacancy_id) WHERE (vacancy_id IS NOT NULL);
CREATE INDEX vacancies_canonical_idx ON public.vacancies USING btree (canonical_fingerprint);
CREATE INDEX vacancies_normalization_queue_idx ON public.vacancies USING btree (lifecycle_status, normalization_retry_at, published_at);
CREATE INDEX vacancies_search_idx ON public.vacancies USING gin (search_vector);
