steps:
  - name: gcr.io/cloud-builders/docker
    args: [build, --target, web, --tag, '${_WEB_IMAGE}', .]
  - name: gcr.io/cloud-builders/docker
    args: [build, --target, worker, --tag, '${_WORKER_IMAGE}', .]
images:
  - '${_WEB_IMAGE}'
  - '${_WORKER_IMAGE}'
options:
  machineType: E2_HIGHCPU_8
