-- Jobseeker PostgreSQL schema — the single schema of record.
--
-- Applied to an empty database by `jobseeker db init` (or psql). There are no incremental migrations: a schema
-- change ships as a new revision of this file plus, when needed, a documented one-off statement for live
-- deployments.


create table public.users (
  user_id text not null,
  chat_id text not null,
  username text,
  display_name text not null,
  status text not null,
  is_owner smallint not null default 0,
  requested_at timestamptz,
  approved_at timestamptz,
  updated_at timestamptz not null,
  delivery_start_minutes integer,
  delivery_end_minutes integer,
  digest_minutes integer,
  delivery_timezone text,
  last_digest_at timestamptz,
  -- Interface language: the one chosen with /language, or the Telegram client language first seen for this user.
  -- Null means the deployment default; an unrecognised value is read as the default rather than rejected.
  locale text,
  constraint users_is_owner_check check (is_owner = any (array[0, 1])),
  constraint users_status_check check (status = any (array['unregistered','pending','approved','rejected','revoked'])),
  constraint users_pkey primary key (user_id),
  constraint users_chat_id_key unique (chat_id)
);

create table public.cv_documents (
  user_id text not null,
  cv_sha256 text not null,
  cv_text text not null,
  document_json jsonb not null,
  source_format text not null,
  original_filename text not null,
  media_type text not null,
  parser_name text not null,
  parser_version text not null,
  -- The per-platform LLM-generated search profiles: the source that demand compilation reads.
  search_profiles jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null,
  constraint cv_documents_pkey primary key (user_id),
  constraint cv_documents_user_id_fkey foreign key (user_id) references users(user_id) on delete cascade
);

create table public.vacancies (
  id bigint generated by default as identity,
  source text not null,
  source_id text not null,
  apply_id text,
  name text,
  employer text,
  area text,
  salary_from integer,
  salary_to integer,
  salary_currency text,
  salary_gross smallint,
  experience text,
  employment text,
  schedule text,
  work_format text,
  description text,
  key_skills_json jsonb,
  url text not null,
  published_at timestamptz not null,
  source_query text,
  content_hash text,
  canonical_fingerprint text,
  first_seen_at timestamptz not null,
  updated_at timestamptz not null,
  search_vector tsvector generated always as (to_tsvector('simple'::regconfig, ((((((coalesce(name, ''::text) || ' '::text) || coalesce(employer, ''::text)) || ' '::text) || coalesce(description, ''::text)) || ' '::text) || coalesce((key_skills_json)::text, ''::text)))) stored,
  listing_search_name text,
  listing_title text,
  listing_summary text,
  listing_payload jsonb,
  listing_hash text,
  lifecycle_status text,
  normalized_vacancy_id bigint,
  normalization_attempts integer not null default 0,
  normalization_error text,
  normalization_retry_at timestamptz,
  last_seen_at timestamptz,
  last_checked_at timestamptz,
  constraint vacancies_apply_id_check check (apply_id ~ '^[a-z]{6}$'::text),
  constraint vacancies_lifecycle_status_check check (lifecycle_status = any (array['discovered','queued','filtered','normalizing','normalized','duplicate','failed','closed'])),
  constraint vacancies_salary_gross_check check ((salary_gross is null) or (salary_gross = any (array[0, 1]))),
  constraint vacancies_pkey primary key (id),
  constraint vacancies_apply_id_key unique (apply_id),
  constraint vacancies_source_source_id_key unique (source, source_id),
  constraint vacancies_normalized_vacancy_id_fkey foreign key (normalized_vacancy_id) references vacancies(id) on delete set null
);

create table public.search_units (
  unit_id text not null,
  platform text not null,
  filter_signature text not null,
  canonical_tokens text[] not null,
  query jsonb not null,
  cadence_minutes integer not null,
  next_run_at timestamptz not null,
  last_run_at timestamptz,
  last_novelty_at timestamptz,
  created_at timestamptz not null default now(),
  retired_at timestamptz,
  constraint search_units_pkey primary key (unit_id)
);

create table public.unit_subscriptions (
  unit_id text not null,
  user_id text not null,
  search_name text not null,
  source_search jsonb not null,
  created_at timestamptz not null default now(),
  constraint unit_subscriptions_pkey primary key (unit_id, user_id),
  constraint unit_subscriptions_unit_id_fkey foreign key (unit_id) references search_units(unit_id) on delete cascade,
  constraint unit_subscriptions_user_id_fkey foreign key (user_id) references users(user_id) on delete cascade
);

create table public.matches (
  user_id text not null,
  vacancy_id bigint not null,
  state text not null default 'matched',
  lexical_score integer,
  -- The prefilter evidence exactly as it stood at match time. Paired with llm_score these rows are the
  -- calibration's training data; they are never recomputed, because the CV may have changed since.
  lexical_regex_score integer,
  lexical_cosine double precision,
  -- The two signals lexical_regex_score collapses together, kept apart so a refit can weigh them separately.
  -- Both 0..1; null on rows matched before these columns existed.
  lexical_title_similarity double precision,
  lexical_skill_coverage double precision,
  llm_score integer,
  score_updated_at timestamptz,
  alert_primary_track text,
  alert_summary text,
  alert_reasons jsonb,
  alert_gaps jsonb,
  application_status text,
  application_error text,
  application_requested_at timestamptz,
  application_updated_at timestamptz,
  -- Delivered artifacts by kind: the Telegram file_id (cv) or text (letter) plus the cv hash it was built from,
  -- so a repeat request resends instantly instead of regenerating.
  application_artifacts jsonb not null default '{}'::jsonb,
  matched_at timestamptz not null,
  updated_at timestamptz not null,
  constraint matches_state_check check (state = any (array['matched','queued','scored','alerted','digested','skipped','applying','applied','expired'])),
  constraint matches_application_status_check check (application_status = any (array['generating','ready','failed'])),
  constraint matches_llm_score_check check ((llm_score >= 0) and (llm_score <= 100)),
  constraint matches_pkey primary key (user_id, vacancy_id),
  constraint matches_user_id_fkey foreign key (user_id) references users(user_id) on delete cascade,
  constraint matches_vacancy_id_fkey foreign key (vacancy_id) references vacancies(id) on delete cascade
);

-- Role-token equivalences mined from career-profile title variants (engine mineRoleEquivalences). Consulted at
-- compare time by the prefilter and unit adoption; never by unit-identity hashing. Rebuilt from profiles, so
-- rows are derived data — truncating this table only narrows matching until the next mining pass.
create table public.role_equivalences (
  token_a text not null,
  token_b text not null,
  support integer not null default 1,
  updated_at timestamptz not null default now(),
  constraint role_equivalences_pkey primary key (token_a, token_b),
  constraint role_equivalences_order_check check (token_a < token_b)
);

-- Every calibration the refit stage ever produced, accepted or not; the active model is the newest accepted
-- row, and rolling back is flipping accepted off. Coefficients follow the engine's prefilterCalibrationSchema.
create table public.calibrations (
  id bigint generated by default as identity,
  created_at timestamptz not null default now(),
  coefficients jsonb not null,
  metrics jsonb not null,
  accepted smallint not null default 0,
  constraint calibrations_accepted_check check (accepted = any (array[0, 1])),
  constraint calibrations_pkey primary key (id)
);

create table public.usage_events (
  id bigint generated by default as identity,
  user_id text not null,
  kind text not null,
  occurred_at timestamptz not null,
  agent text,
  model text,
  input_tokens bigint not null default 0,
  output_tokens bigint not null default 0,
  cache_read_tokens bigint not null default 0,
  cache_write_tokens bigint not null default 0,
  total_tokens bigint not null default 0,
  cost_usd numeric(14,8) not null default 0,
  constraint usage_events_kind_check check (kind = any (array['score','application','search-profile','llm'])),
  constraint usage_events_pkey primary key (id),
  constraint usage_events_user_id_fkey foreign key (user_id) references users(user_id) on delete cascade
);

create table public.accounts (
  user_id text not null,
  day date not null,
  llm_cost_usd numeric(14,8) not null default 0,
  scores integer not null default 0,
  applications integer not null default 0,
  search_profiles integer not null default 0,
  updated_at timestamptz not null default now(),
  constraint accounts_pkey primary key (user_id, day),
  constraint accounts_user_id_fkey foreign key (user_id) references users(user_id) on delete cascade
);

create table public.user_state (
  user_id text not null,
  kind text not null,
  state jsonb not null default '{}'::jsonb,
  expires_at timestamptz not null,
  updated_at timestamptz not null default now(),
  constraint user_state_pkey primary key (user_id, kind),
  constraint user_state_user_id_fkey foreign key (user_id) references users(user_id) on delete cascade
);

create table public.telegram_updates (
  update_id bigint not null,
  received_at timestamptz not null default now(),
  state text not null default 'processing',
  attempts integer not null default 1,
  lease_expires_at timestamptz,
  completed_at timestamptz,
  last_error text,
  constraint telegram_updates_state_check check (state = any (array['processing','completed','failed'])),
  constraint telegram_updates_pkey primary key (update_id)
);

create index telegram_updates_cleanup_idx on public.telegram_updates using btree (received_at);
create index usage_events_kind_time_idx on public.usage_events using btree (kind, occurred_at desc);
create index usage_events_user_kind_time_idx on public.usage_events using btree (user_id, kind, occurred_at desc);
create index user_state_expiry_idx on public.user_state using btree (expires_at);
create index matches_user_state_idx on public.matches using btree (user_id, state);
create index matches_user_score_idx on public.matches using btree (user_id, llm_score desc) where (llm_score is not null);
create index search_units_due_idx on public.search_units using btree (platform, next_run_at) where (retired_at is null);
create index vacancies_canonical_idx on public.vacancies using btree (canonical_fingerprint);
create index vacancies_normalization_queue_idx on public.vacancies using btree (lifecycle_status, normalization_retry_at, published_at);
create index vacancies_search_idx on public.vacancies using gin (search_vector);
