-- Application-owned schema. Flue creates and versions its own flue_* tables.
-- All timestamps remain ISO-8601 text during the SQLite-to-Postgres transition.

create table if not exists public.telegram_users (
  user_id text primary key,
  chat_id text not null unique,
  username text,
  display_name text not null,
  status text not null check (status in ('unregistered','pending','approved','rejected','revoked')),
  is_owner smallint not null default 0 check (is_owner in (0,1)),
  requested_at text,
  approved_at text,
  updated_at text not null
);

create table if not exists public.app_migrations (
  name text primary key,
  applied_at text not null
);

create table if not exists public.cv_templates (
  user_id text primary key references public.telegram_users(user_id) on delete cascade,
  cv_sha256 text not null,
  cv_text text not null,
  document_json text not null,
  source_format text not null check (source_format in ('pdf','md','txt','doc','docx')),
  original_filename text not null,
  media_type text not null,
  parser_name text not null,
  parser_version text not null,
  updated_at text not null
);

create table if not exists public.search_profiles (
  user_id text not null references public.telegram_users(user_id) on delete cascade,
  platform text not null,
  profile_json text not null,
  updated_at text not null,
  primary key (user_id, platform)
);

create table if not exists public.global_scheduler_settings (
  name text primary key check (name in ('scrape','notify','digest')),
  cron text not null,
  updated_at text not null
);

create table if not exists public.user_delivery_windows (
  user_id text primary key references public.telegram_users(user_id) on delete cascade,
  start_minutes integer not null check (start_minutes between 0 and 1439),
  end_minutes integer not null check (end_minutes between 0 and 1439),
  digest_minutes integer not null default 540 check (digest_minutes between 0 and 1439),
  timezone text not null,
  last_digest_at text,
  updated_at text not null
);

create table if not exists public.pending_deliveries (
  user_id text not null references public.telegram_users(user_id) on delete cascade,
  kind text not null check (kind in ('notify','digest')),
  queued_at text not null,
  primary key (user_id, kind)
);

create table if not exists public.vacancies (
  id bigint generated by default as identity primary key,
  hh_id text not null unique,
  source text not null,
  source_id text not null,
  apply_id text not null unique check (apply_id ~ '^[a-z]{6}$'),
  name text not null,
  employer text not null,
  area text not null,
  salary_from integer,
  salary_to integer,
  salary_currency text,
  salary_gross smallint check (salary_gross is null or salary_gross in (0,1)),
  experience text not null,
  employment text not null,
  schedule text not null,
  work_format text not null,
  description text not null,
  key_skills_json text not null,
  url text not null,
  published_at text not null,
  source_query text not null,
  content_hash text not null,
  canonical_fingerprint text,
  decision text not null default 'new' check (decision in ('new','alerted','digested','skipped','applying','applied')),
  first_seen_at text not null,
  updated_at text not null,
  search_vector tsvector generated always as (
    to_tsvector('simple', coalesce(name,'') || ' ' || coalesce(employer,'') || ' ' ||
      coalesce(description,'') || ' ' || coalesce(key_skills_json,''))
  ) stored,
  unique (source, source_id)
);

create table if not exists public.user_vacancies (
  user_id text not null references public.telegram_users(user_id) on delete cascade,
  vacancy_id bigint not null references public.vacancies(id) on delete cascade,
  decision text not null default 'new' check (decision in ('new','alerted','digested','skipped','applying','applied')),
  first_relevant_at text not null,
  score_updated_at text,
  updated_at text not null,
  primary key (user_id, vacancy_id)
);

create table if not exists public.scores (
  user_id text not null references public.telegram_users(user_id) on delete cascade,
  vacancy_id bigint not null references public.vacancies(id) on delete cascade,
  score integer not null check (score between 0 and 100),
  primary key (user_id, vacancy_id)
);

create table if not exists public.score_alert_details (
  user_id text not null,
  vacancy_id bigint not null,
  primary_track text not null check (length(trim(primary_track)) between 1 and 80),
  summary text not null,
  reasons_json text not null,
  gaps_json text not null,
  primary key (user_id, vacancy_id),
  foreign key (user_id, vacancy_id) references public.scores(user_id, vacancy_id) on delete cascade
);

create table if not exists public.prefilter_scores (
  user_id text not null references public.telegram_users(user_id) on delete cascade,
  vacancy_id bigint not null references public.vacancies(id) on delete cascade,
  context_hash text not null,
  content_hash text not null,
  regex_score integer not null check (regex_score between 0 and 100),
  embedding_cosine double precision not null,
  embedding_score integer not null check (embedding_score between 0 and 100),
  semantic_cosine double precision,
  semantic_score integer,
  semantic_status text not null default 'disabled' check (semantic_status in ('ready','skipped','disabled','unavailable')),
  combined_score integer not null check (combined_score between 0 and 100),
  filtered smallint not null check (filtered in (0,1)),
  audit_selected smallint not null default 0 check (audit_selected in (0,1)),
  reasons_json text not null,
  scored_at text not null,
  primary key (user_id, vacancy_id)
);

create table if not exists public.embedding_cache (
  model text not null,
  kind text not null check (kind in ('cv','vacancy')),
  user_id text not null,
  content_hash text not null,
  dimensions integer not null,
  vector bytea not null,
  created_at text not null,
  check ((kind='vacancy' and user_id='') or (kind='cv' and length(user_id)>0)),
  primary key (model, kind, user_id, content_hash)
);

create table if not exists public.vacancy_candidates (
  source text not null,
  source_id text not null,
  url text not null,
  search_name text not null,
  title text not null,
  summary text not null,
  published_at text not null,
  payload_json text not null,
  listing_hash text not null,
  status text not null check (status in ('discovered','queued','filtered','normalizing','normalized','duplicate','failed','closed')),
  vacancy_id bigint references public.vacancies(id) on delete set null,
  prefilter_context_hash text,
  regex_score integer,
  lexical_cosine double precision,
  semantic_cosine double precision,
  semantic_status text not null default 'disabled' check (semantic_status in ('ready','skipped','disabled','unavailable')),
  combined_score integer,
  filter_reasons_json text,
  attempts integer not null default 0,
  last_error text,
  next_retry_at text,
  first_seen_at text not null,
  last_seen_at text not null,
  last_checked_at text,
  primary key (source, source_id)
);

create table if not exists public.candidate_discoveries (
  user_id text not null references public.telegram_users(user_id) on delete cascade,
  source text not null,
  source_id text not null,
  search_name text not null,
  first_seen_at text not null,
  last_seen_at text not null,
  primary key (user_id, source, source_id),
  foreign key (source, source_id) references public.vacancy_candidates(source, source_id) on delete cascade
);

create table if not exists public.applications (
  user_id text not null references public.telegram_users(user_id) on delete cascade,
  vacancy_id bigint not null references public.vacancies(id) on delete cascade,
  status text not null check (status in ('generating','ready','failed')),
  error text,
  requested_at text not null,
  updated_at text not null,
  primary key (user_id, vacancy_id)
);

create table if not exists public.usage_events (
  id bigint generated by default as identity primary key,
  user_id text not null references public.telegram_users(user_id) on delete cascade,
  kind text not null check (kind in ('score','application','search-profile')),
  occurred_at text not null
);

-- Durable coordination for webhook retries, Cloud Tasks, scheduler leases, and paid fallback budgets.
create table if not exists public.telegram_update_receipts (
  update_id bigint primary key,
  received_at timestamptz not null default now()
);

create table if not exists public.telegram_sessions (
  user_id text not null references public.telegram_users(user_id) on delete cascade,
  kind text not null,
  state jsonb not null default '{}'::jsonb,
  expires_at timestamptz not null,
  updated_at timestamptz not null default now(),
  primary key (user_id, kind)
);

create table if not exists public.background_tasks (
  task_key text primary key,
  kind text not null,
  user_id text references public.telegram_users(user_id) on delete cascade,
  state text not null check (state in ('queued','running','completed','failed','cancelled')),
  payload jsonb not null default '{}'::jsonb,
  attempts integer not null default 0,
  lease_owner text,
  lease_expires_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.llm_cost_events (
  id bigint generated always as identity primary key,
  provider text not null,
  model text not null,
  purpose text not null,
  user_id text references public.telegram_users(user_id) on delete set null,
  input_tokens bigint not null check (input_tokens >= 0),
  output_tokens bigint not null check (output_tokens >= 0),
  cache_read_tokens bigint not null check (cache_read_tokens >= 0),
  cost_usd numeric(14,8) not null check (cost_usd >= 0),
  used_api_fallback boolean not null default false,
  occurred_at timestamptz not null default now()
);

create index if not exists vacancies_canonical_idx on public.vacancies(canonical_fingerprint);
create index if not exists vacancies_search_idx on public.vacancies using gin(search_vector);
create index if not exists user_vacancies_decision_idx on public.user_vacancies(user_id,decision);
create index if not exists scores_user_score_idx on public.scores(user_id,score desc);
create index if not exists prefilter_queue_idx on public.prefilter_scores(user_id,context_hash,filtered,combined_score desc);
create index if not exists candidate_queue_idx on public.vacancy_candidates(status,combined_score desc,published_at desc);
create index if not exists candidate_discoveries_user_idx on public.candidate_discoveries(user_id,last_seen_at desc);
create index if not exists usage_events_user_kind_time_idx on public.usage_events(user_id,kind,occurred_at desc);
create index if not exists telegram_sessions_expiry_idx on public.telegram_sessions(expires_at);
create index if not exists background_tasks_queue_idx on public.background_tasks(state,created_at);
create index if not exists llm_cost_events_time_idx on public.llm_cost_events(occurred_at);
create index if not exists llm_cost_events_fallback_time_idx on public.llm_cost_events(used_api_fallback,occurred_at);

-- Direct Postgres connections use the postgres role. Data API roles receive no access.
revoke all on all tables in schema public from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;
